# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/user/Área de Trabalho/Teste/lerImagem"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/user/Área de Trabalho/Teste/lerImagem"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/user/Área de Trabalho/Teste/lerImagem/CMakeFiles" "/home/user/Área de Trabalho/Teste/lerImagem/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/user/Área de Trabalho/Teste/lerImagem/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lerImagem

# Build rule for target.
lerImagem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lerImagem
.PHONY : lerImagem

# fast build rule for target.
lerImagem/fast:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/build
.PHONY : lerImagem/fast

src/altura.o: src/altura.cpp.o

.PHONY : src/altura.o

# target to build an object file
src/altura.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/altura.cpp.o
.PHONY : src/altura.cpp.o

src/altura.i: src/altura.cpp.i

.PHONY : src/altura.i

# target to preprocess a source file
src/altura.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/altura.cpp.i
.PHONY : src/altura.cpp.i

src/altura.s: src/altura.cpp.s

.PHONY : src/altura.s

# target to generate assembly for a file
src/altura.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/altura.cpp.s
.PHONY : src/altura.cpp.s

src/auction.o: src/auction.cpp.o

.PHONY : src/auction.o

# target to build an object file
src/auction.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/auction.cpp.o
.PHONY : src/auction.cpp.o

src/auction.i: src/auction.cpp.i

.PHONY : src/auction.i

# target to preprocess a source file
src/auction.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/auction.cpp.i
.PHONY : src/auction.cpp.i

src/auction.s: src/auction.cpp.s

.PHONY : src/auction.s

# target to generate assembly for a file
src/auction.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/auction.cpp.s
.PHONY : src/auction.cpp.s

src/circles_data.o: src/circles_data.cpp.o

.PHONY : src/circles_data.o

# target to build an object file
src/circles_data.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/circles_data.cpp.o
.PHONY : src/circles_data.cpp.o

src/circles_data.i: src/circles_data.cpp.i

.PHONY : src/circles_data.i

# target to preprocess a source file
src/circles_data.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/circles_data.cpp.i
.PHONY : src/circles_data.cpp.i

src/circles_data.s: src/circles_data.cpp.s

.PHONY : src/circles_data.s

# target to generate assembly for a file
src/circles_data.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/circles_data.cpp.s
.PHONY : src/circles_data.cpp.s

src/circulos.o: src/circulos.cpp.o

.PHONY : src/circulos.o

# target to build an object file
src/circulos.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/circulos.cpp.o
.PHONY : src/circulos.cpp.o

src/circulos.i: src/circulos.cpp.i

.PHONY : src/circulos.i

# target to preprocess a source file
src/circulos.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/circulos.cpp.i
.PHONY : src/circulos.cpp.i

src/circulos.s: src/circulos.cpp.s

.PHONY : src/circulos.s

# target to generate assembly for a file
src/circulos.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/circulos.cpp.s
.PHONY : src/circulos.cpp.s

src/eulerianField.o: src/eulerianField.cpp.o

.PHONY : src/eulerianField.o

# target to build an object file
src/eulerianField.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/eulerianField.cpp.o
.PHONY : src/eulerianField.cpp.o

src/eulerianField.i: src/eulerianField.cpp.i

.PHONY : src/eulerianField.i

# target to preprocess a source file
src/eulerianField.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/eulerianField.cpp.i
.PHONY : src/eulerianField.cpp.i

src/eulerianField.s: src/eulerianField.cpp.s

.PHONY : src/eulerianField.s

# target to generate assembly for a file
src/eulerianField.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/eulerianField.cpp.s
.PHONY : src/eulerianField.cpp.s

src/eulerianFieldSimulation.o: src/eulerianFieldSimulation.cpp.o

.PHONY : src/eulerianFieldSimulation.o

# target to build an object file
src/eulerianFieldSimulation.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/eulerianFieldSimulation.cpp.o
.PHONY : src/eulerianFieldSimulation.cpp.o

src/eulerianFieldSimulation.i: src/eulerianFieldSimulation.cpp.i

.PHONY : src/eulerianFieldSimulation.i

# target to preprocess a source file
src/eulerianFieldSimulation.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/eulerianFieldSimulation.cpp.i
.PHONY : src/eulerianFieldSimulation.cpp.i

src/eulerianFieldSimulation.s: src/eulerianFieldSimulation.cpp.s

.PHONY : src/eulerianFieldSimulation.s

# target to generate assembly for a file
src/eulerianFieldSimulation.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/eulerianFieldSimulation.cpp.s
.PHONY : src/eulerianFieldSimulation.cpp.s

src/hough.o: src/hough.cpp.o

.PHONY : src/hough.o

# target to build an object file
src/hough.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/hough.cpp.o
.PHONY : src/hough.cpp.o

src/hough.i: src/hough.cpp.i

.PHONY : src/hough.i

# target to preprocess a source file
src/hough.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/hough.cpp.i
.PHONY : src/hough.cpp.i

src/hough.s: src/hough.cpp.s

.PHONY : src/hough.s

# target to generate assembly for a file
src/hough.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/hough.cpp.s
.PHONY : src/hough.cpp.s

src/lagrangian.o: src/lagrangian.cpp.o

.PHONY : src/lagrangian.o

# target to build an object file
src/lagrangian.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/lagrangian.cpp.o
.PHONY : src/lagrangian.cpp.o

src/lagrangian.i: src/lagrangian.cpp.i

.PHONY : src/lagrangian.i

# target to preprocess a source file
src/lagrangian.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/lagrangian.cpp.i
.PHONY : src/lagrangian.cpp.i

src/lagrangian.s: src/lagrangian.cpp.s

.PHONY : src/lagrangian.s

# target to generate assembly for a file
src/lagrangian.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/lagrangian.cpp.s
.PHONY : src/lagrangian.cpp.s

src/lerImagem.o: src/lerImagem.cpp.o

.PHONY : src/lerImagem.o

# target to build an object file
src/lerImagem.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/lerImagem.cpp.o
.PHONY : src/lerImagem.cpp.o

src/lerImagem.i: src/lerImagem.cpp.i

.PHONY : src/lerImagem.i

# target to preprocess a source file
src/lerImagem.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/lerImagem.cpp.i
.PHONY : src/lerImagem.cpp.i

src/lerImagem.s: src/lerImagem.cpp.s

.PHONY : src/lerImagem.s

# target to generate assembly for a file
src/lerImagem.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/lerImagem.cpp.s
.PHONY : src/lerImagem.cpp.s

src/mixing.o: src/mixing.cpp.o

.PHONY : src/mixing.o

# target to build an object file
src/mixing.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/mixing.cpp.o
.PHONY : src/mixing.cpp.o

src/mixing.i: src/mixing.cpp.i

.PHONY : src/mixing.i

# target to preprocess a source file
src/mixing.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/mixing.cpp.i
.PHONY : src/mixing.cpp.i

src/mixing.s: src/mixing.cpp.s

.PHONY : src/mixing.s

# target to generate assembly for a file
src/mixing.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/mixing.cpp.s
.PHONY : src/mixing.cpp.s

src/preProcess.o: src/preProcess.cpp.o

.PHONY : src/preProcess.o

# target to build an object file
src/preProcess.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/preProcess.cpp.o
.PHONY : src/preProcess.cpp.o

src/preProcess.i: src/preProcess.cpp.i

.PHONY : src/preProcess.i

# target to preprocess a source file
src/preProcess.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/preProcess.cpp.i
.PHONY : src/preProcess.cpp.i

src/preProcess.s: src/preProcess.cpp.s

.PHONY : src/preProcess.s

# target to generate assembly for a file
src/preProcess.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/preProcess.cpp.s
.PHONY : src/preProcess.cpp.s

src/read_control.o: src/read_control.cpp.o

.PHONY : src/read_control.o

# target to build an object file
src/read_control.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/read_control.cpp.o
.PHONY : src/read_control.cpp.o

src/read_control.i: src/read_control.cpp.i

.PHONY : src/read_control.i

# target to preprocess a source file
src/read_control.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/read_control.cpp.i
.PHONY : src/read_control.cpp.i

src/read_control.s: src/read_control.cpp.s

.PHONY : src/read_control.s

# target to generate assembly for a file
src/read_control.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/read_control.cpp.s
.PHONY : src/read_control.cpp.s

src/simulation.o: src/simulation.cpp.o

.PHONY : src/simulation.o

# target to build an object file
src/simulation.cpp.o:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/simulation.cpp.o
.PHONY : src/simulation.cpp.o

src/simulation.i: src/simulation.cpp.i

.PHONY : src/simulation.i

# target to preprocess a source file
src/simulation.cpp.i:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/simulation.cpp.i
.PHONY : src/simulation.cpp.i

src/simulation.s: src/simulation.cpp.s

.PHONY : src/simulation.s

# target to generate assembly for a file
src/simulation.cpp.s:
	$(MAKE) -f CMakeFiles/lerImagem.dir/build.make CMakeFiles/lerImagem.dir/src/simulation.cpp.s
.PHONY : src/simulation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lerImagem"
	@echo "... edit_cache"
	@echo "... src/altura.o"
	@echo "... src/altura.i"
	@echo "... src/altura.s"
	@echo "... src/auction.o"
	@echo "... src/auction.i"
	@echo "... src/auction.s"
	@echo "... src/circles_data.o"
	@echo "... src/circles_data.i"
	@echo "... src/circles_data.s"
	@echo "... src/circulos.o"
	@echo "... src/circulos.i"
	@echo "... src/circulos.s"
	@echo "... src/eulerianField.o"
	@echo "... src/eulerianField.i"
	@echo "... src/eulerianField.s"
	@echo "... src/eulerianFieldSimulation.o"
	@echo "... src/eulerianFieldSimulation.i"
	@echo "... src/eulerianFieldSimulation.s"
	@echo "... src/hough.o"
	@echo "... src/hough.i"
	@echo "... src/hough.s"
	@echo "... src/lagrangian.o"
	@echo "... src/lagrangian.i"
	@echo "... src/lagrangian.s"
	@echo "... src/lerImagem.o"
	@echo "... src/lerImagem.i"
	@echo "... src/lerImagem.s"
	@echo "... src/mixing.o"
	@echo "... src/mixing.i"
	@echo "... src/mixing.s"
	@echo "... src/preProcess.o"
	@echo "... src/preProcess.i"
	@echo "... src/preProcess.s"
	@echo "... src/read_control.o"
	@echo "... src/read_control.i"
	@echo "... src/read_control.s"
	@echo "... src/simulation.o"
	@echo "... src/simulation.i"
	@echo "... src/simulation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

